name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Run Android Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis_playstore
        arch: x86
        profile: Nexus 6
        script: |
          echo "Current Directory:"
          pwd  # 현재 작업 디렉토리 출력
          echo "Listing Files:"
          ls -la  # 현재 디렉토리의 파일 목록 출력
          ./gradlew connectedAndroidTest --stacktrace
        working-directory: source/did-client-sdk-aos  # 경로를 명시적으로 지정 
