name: Android Instrumentation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-test:
    runs-on: ubuntu-latest  # Linux 러너 사용
    timeout-minutes: 60

    defaults:
      run:
        working-directory: source/did-client-sdk-aos

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: pixel_6
        working-directory: source/did-client-sdk-aos
        script: |
          adb devices
          ./gradlew connectedAndroidTest

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: source/did-client-sdk-aos/app/build/outputs/androidTest-results
