name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Install Dependencies
      run: |
        cd source/did-client-sdk-aos
        ./gradlew dependencies
    
    - name: Build with Gradle
      run: |
        cd source/did-client-sdk-aos
        ./gradlew assembleDebug
        
    - name: Run tests with Gradle
      run: |
        cd source/did-client-sdk-aos
        ./gradlew test

    - name: Build utility module with Gradle
      run: |
        cd source/did-client-sdk-aos/did-utility-sdk-aos
        ./gradlew assembleDebug

    - name: Run unit tests for utility module with Gradle
      run: |
        cd source/did-client-sdk-aos/did-utility-sdk-aos
        ./gradlew connectedAndroidTest
      
