name: Android Instrumentation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-test:
    runs-on: macos-latest
    timeout-minutes: 45  # 전체 작업 시간 제한 증가

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create and start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29  # API 레벨을 낮춤 (29 = Android 10)
        arch: x86_64
        profile: Nexus 6  # 더 가벼운 디바이스 프로필 사용
        script: |
          echo "Emulator is up and running"
          adb devices
          # 에뮬레이터 상태 확인
          adb shell getprop sys.boot_completed
          # ADB 서버 재시작
          adb kill-server
          adb start-server
          # Instrumentation 테스트 실행
          ./gradlew connectedCheck
        working-directory: source/did-client-sdk-aos  
        emulator-options: |
          -no-snapshot-save
          -no-window
          -gpu swiftshader_indirect
          -noaudio
          -no-boot-anim
          -camera-back none
        disable-animations: true
        verbose: true
        force-avd-creation: false
        emulator-boot-timeout: 1200  # 20분으로 증가
        disk-size: 2000M

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: app/build/outputs/androidTest-results
