name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    # 3. Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    # 4. Download dependencies
    - name: Install Dependencies
      run: ./gradlew dependencies

    # 5. Start Android Emulator for API level 34
    - name: Run Instrumentation Tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 34                # API Level 34 (Android 14)
        target: google_apis           # Use Google APIs image
        arch: x86_64                  # x86_64 architecture for 64-bit testing
        profile: nexus_5              # You can specify device profile, e.g., Nexus 5
        script: ./gradlew connectedAndroidTest
        working-directory: source/did-client-sdk-aos
        disable-animations: true      # Optional: Disable animations for faster tests
        emulator-options: -no-window  # Optional: Run emulator in headless mode

    # 6. Stop Emulator
    - name: Kill Emulator
      run: adb emu kill
