name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        target: default
        arch: x86
        profile: Nexus 6
        script: |
          cd source/did-client-sdk-aos
          ./gradlew connectedAndroidTest --stacktrace

    - name: Build utility module with Gradle
      run: |
        cd source/did-client-sdk-aos
        ./gradlew -p did-utility-sdk-aos assembleDebug
      
